# fly.toml app configuration file generated for cityborn-backend-staging on 2025-06-24T11:31:16+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cityborn-backend-staging'
primary_region = 'cdg'

[build]

[env]
  CORS_ORIGIN = 'https://cityborn.tpicaud.xyz'
  NODE_ENV = 'staging'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
