export enum ErrorCode {

    /////////////////////
    // Client friendly //
    /////////////////////

    // User
    USER_NOT_FOUND = "USER_NOT_FOUND",
    USER_INVALID_CREDENTIALS = "USER_INVALID_CREDENTIALS",
    USER_USERNAME_ALREADY_EXISTS = "USER_USERNAME_ALREADY_EXISTS",
    USER_EMAIL_ALREADY_TAKEN = "USER_EMAIL_ALREADY_TAKEN",
    USER_NOT_VANILLA_ACCOUNT = "USER_NOT_VANILLA_ACCOUNT",
    USER_GOOGLE_EMAIL_NOT_VERIFIED = "USER_GOOGLE_EMAIL_NOT_VERIFIED",
    USER_REFRESH_FAILED = "USER_REFRESH_FAILED",
    USER_NOT_VERIFIED = "USER_NOT_VERIFIED",
    USER_TOKEN_MISSING = "USER_TOKEN_MISSING",
    USER_INVALID_TOKEN = "USER_INVALID_TOKEN",
    USER_VERIFICATION_EMAIL_INVALID_TOKEN = "USER_VERIFICATION_EMAIL_INVALID_TOKEN",
    USER_NO_ACCOUNT_OR_NOT_VERIFIED = "USER_NO_ACCOUNT_OR_NOT_VERIFIED",

    // Player
    PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND",

    // Session
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
    SESSION_PLAYER_NOT_FOUND = "SESSION_PLAYER_NOT_FOUND",
    SESSION_PLAYER_NOT_CONNECTED = "SESSION_PLAYER_NOT_CONNECTED",
    SESSION_PLAYER_ALREADY_EXISTS = 'SESSION_PLAYER_ALREADY_EXISTS',
    SESSION_CREATION_FAILED = "SESSION_CREATION_FAILED",
    SESSION_FORBIDDEN_HOST = "SESSION_FORBIDDEN_HOST",
    SESSION_NO_CURRENT_GAME = "SESSION_NO_CURRENT_GAME",
    SESSION_ALREADY_IN_GAME = "SESSION_ALREADY_IN_GAME",

    // Game
    GAME_END_SENTENCE_NOT_FOUND = "GAME_END_SENTENCE_NOT_FOUND",
    GAME_NO_ACTIVE_ROUND = "GAME_NO_ACTIVE_ROUND",
    GAME_CREATION_FAILED = "GAME_CREATION_FAILED",

    // Guess objects
    GUESS_OBJECTS_NOT_FOUND = "GUESS_OBJECTS_NOT_FOUND",
    GUESS_OBJECTS_GET_FAILED = "GUESS_OBJECTS_GET_FAILED",
    GUESS_OBJECTS_SEARCH_FAILED = "GUESS_OBJECTS_SEARCH_FAILED",

    // World location
    WORLD_LOCATION_SEARCH_FAILED = "WORLD_LOCATION_SEARCH_FAILED",
    WORLD_LOCATION_NOT_FOUND = "WORLD_LOCATION_NOT_FOUND",


    ///////////////
    // Technical //
    ///////////////

    // Redis
    REDIS_GET_FAILED = "REDIS_GET_FAILED",
    REDIS_SET_FAILED = "REDIS_SAVE_FAILED",
    REDIS_DELETE_FAILED = "REDIS_DELETE_FAILED",

    // Email
    EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED",

    // Classic error codes
    BAD_REQUEST = "BAD_REQUEST",

    // Default
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
}
