name: Build Staging Android App

on:
  push:
    branches:
      - staging
    paths:
      - 'apps/mobile/**'
      - 'packages/types/**'
      - 'package/errors/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Mobile - Staging
    env:
      APP_VARIANT: ${{ vars.APP_VARIANT }}
      APP_ID: ${{vars.APP_ID}}
      GOOGLE_MAPS_ANDROID_API_KEY: ${{ secrets.GOOGLE_MAPS_ANDROID_API_KEY }}
      GOOGLE_MAPS_IOS_API_KEY: ${{ secrets.GOOGLE_MAPS_IOS_API_KEY }}
      EXPO_PUBLIC_REST_BACKEND_URL: ${{vars.EXPO_PUBLIC_REST_BACKEND_URL}}
      EXPO_PUBLIC_WEBSOCKET_BACKEND_URL: ${{vars.EXPO_PUBLIC_WEBSOCKET_BACKEND_URL}}
      EXPO_PUBLIC_GOOGLE_OAUTH_WEB_CLIENT_ID: ${{vars.EXPO_PUBLIC_GOOGLE_OAUTH_WEB_CLIENT_ID}}
      EXPO_PUBLIC_GOOGLE_OAUTH_IOS_CLIENT_ID: ${{vars.EXPO_PUBLIC_GOOGLE_OAUTH_IOS_CLIENT_ID}}

    steps:
      - name: Delete unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Check environment variables
        working-directory: apps/mobile
        run: pnpm check-env

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: pnpm install

      - name: Syncing app version code
        working-directory: apps/mobile
        run: eas build:version:sync --platform android --profile staging

      - name: Compute APK name
        id: apk
        working-directory: apps/mobile
        run: |
          VERSION=$(npx expo config --json | jq -r '.version')
          VERSION_CODE=$(eas build:version:get -p android --json --non-interactive | jq -r '.versionCode')

          APK_NAME=cityborn_staging_v${VERSION}_${VERSION_CODE}.apk
          APK_PATH=${{ github.workspace }}/${APK_NAME}

          echo "apk_name=$APK_NAME" >> $GITHUB_OUTPUT
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT

          echo "Computed APK name: $APK_NAME"

      - name: Build Android app
        working-directory: apps/mobile
        run: eas build --platform android --profile staging --local --output ${{steps.apk.outputs.apk_path}}

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.apk.outputs.apk_name}}
          path: ${{steps.apk.outputs.apk_path}}
