name: Build App
on:
  push:
    branches:
      - feature/expo-app_test-workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x]
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 👷 Build app
        run: |
          eas build --local \
            --non-interactive \
            --output=./app-build \
            --platform=android \
            --profile=staging

      - name: 📱 Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: app-android
          path: app-build
