name: Build Staging Android App

on:
  push:
    branches:
      - staging
    paths:
      - 'apps/mobile/**'
      - 'packages/types/**'
      - 'package/errors/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Mobile - Staging
    env:
      APP_VARIANT: ${{ vars.APP_VARIANT }}
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
    steps:
      - name: Delete unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: Check environment variables
        working-directory: apps/mobile
        run: node scripts/check-end.js

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: pnpm install

      - name: Syncing app version code
        working-directory: apps/mobile
        run: eas build:version:sync --platform android --profile staging

      - name: Build Android app
        working-directory: apps/mobile
        run: eas build --platform android --profile staging --local --output ${{ github.workspace }}/cityborn-staging-release.aab

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ github.workspace }}/cityborn-staging-release.aab

      - name: Submit
        working-directory: apps/mobile
        run: eas submit --platform android --profile staging --non-interactive --path ${{ github.workspace }}/cityborn-staging-release.aab
