name: Build Android App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to build'
        required: true
        type: choice
        options:
          - staging
          - production
      profile:
        description: 'EAS profile to use'
        required: true
        type: choice
        options:
          - staging
          - production
          - preview
  workflow_call:
    inputs:
      environment:
        description: 'Environment to build'
        required: true
        type: string
      profile:
        description: 'EAS profile to use'
        required: true
        type: string
    outputs:
      apk_artifact_name:
        value: ${{ jobs.build.outputs.apk_artifact_name }}
    secrets:
      EXPO_TOKEN:
        required: true
      GOOGLE_MAPS_ANDROID_API_KEY:
        required: false
      GOOGLE_MAPS_IOS_API_KEY:
        required: false

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      APP_VARIANT: ${{ vars.APP_VARIANT }}
      APP_ID: ${{ vars.APP_ID }}
      GOOGLE_MAPS_ANDROID_API_KEY: ${{ secrets.GOOGLE_MAPS_ANDROID_API_KEY }}
      GOOGLE_MAPS_IOS_API_KEY: ${{ secrets.GOOGLE_MAPS_IOS_API_KEY }}
      EXPO_PUBLIC_REST_BACKEND_URL: ${{ vars.EXPO_PUBLIC_REST_BACKEND_URL }}
      EXPO_PUBLIC_WEBSOCKET_BACKEND_URL: ${{ vars.EXPO_PUBLIC_WEBSOCKET_BACKEND_URL }}
      EXPO_PUBLIC_GOOGLE_OAUTH_WEB_CLIENT_ID: ${{ vars.EXPO_PUBLIC_GOOGLE_OAUTH_WEB_CLIENT_ID }}
      EXPO_PUBLIC_GOOGLE_OAUTH_IOS_CLIENT_ID: ${{ vars.EXPO_PUBLIC_GOOGLE_OAUTH_IOS_CLIENT_ID }}
    outputs:
      apk_artifact_name: ${{ steps.apk.outputs.apk_name }}

    steps:
      - name: Delete unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Setup repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Check environment variables
        if: inputs.profile != 'preview'
        working-directory: apps/mobile
        run: pnpm check-env

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: pnpm install

      - name: Syncing app version code
        if: inputs.profile != 'preview'
        working-directory: apps/mobile
        run: eas build:version:sync --platform android --profile ${{ inputs.profile }}

      - name: Compute APK name
        id: apk
        working-directory: apps/mobile
        run: |
          if [ "${{ inputs.profile }}" = "preview" ]; then
            VERSION=$(npx expo config --json | jq -r '.version')
            VERSION_CODE=$(eas build:version:get -p android --json --non-interactive --profile production | jq -r '.versionCode')

            APK_NAME=cityborn_v${VERSION}+${VERSION_CODE}_preview.apk
            APK_PATH=${{ github.workspace }}/${APK_NAME}

            echo "apk_name=$APK_NAME" >> $GITHUB_OUTPUT
            echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT

            echo "Computed APK name: $APK_NAME"
          elif [ "${{ inputs.profile }}" = "production" ]; then
            VERSION=$(npx expo config --json | jq -r '.version')
            VERSION_CODE=$(eas build:version:get -p android --json --non-interactive --profile production | jq -r '.versionCode')

            AAB_NAME=cityborn_v${VERSION}+${VERSION_CODE}_production.aab
            AAB_PATH=${{ github.workspace }}/${AAB_NAME}

            echo "apk_name=$AAB_NAME" >> $GITHUB_OUTPUT
            echo "apk_path=$AAB_PATH" >> $GITHUB_OUTPUT

            echo "Computed AAB name: $AAB_NAME"
          else
            VERSION=$(npx expo config --json | jq -r '.version')
            VERSION_CODE=$(eas build:version:get -p android --json --non-interactive --profile production | jq -r '.versionCode')

            APK_NAME=cityborn_v${VERSION}+${VERSION_CODE}_staging.apk
            APK_PATH=${{ github.workspace }}/${APK_NAME}

            echo "apk_name=$APK_NAME" >> $GITHUB_OUTPUT
            echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT

            echo "Computed APK name: $APK_NAME"
          fi

      - name: Build Android app
        working-directory: apps/mobile
        run: eas build --platform android --profile ${{ inputs.profile }} --local --non-interactive --output ${{ steps.apk.outputs.apk_path }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.apk.outputs.apk_name }}
          path: ${{ steps.apk.outputs.apk_path }}
          retention-days: 14