name: Build iOS App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to build'
        required: true
        type: choice
        options:
          - development
          - staging
          - production
      profile:
        description: 'EAS profile to use'
        required: true
        type: choice
        options:
          - development
          - staging
          - production
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      profile:
        required: true
        type: string
    secrets:
      EXPO_TOKEN:
        required: true
      GOOGLE_MAPS_ANDROID_API_KEY:
        required: true
      GOOGLE_MAPS_IOS_API_KEY:
        required: true

jobs:
  build:
    name: Build app
    runs-on: macos-latest
    environment: ${{ inputs.environment }}
    env:
      APP_VARIANT: ${{ vars.APP_VARIANT }}
      APP_ID: ${{ vars.APP_ID }}
      GOOGLE_MAPS_ANDROID_API_KEY: ${{ secrets.GOOGLE_MAPS_ANDROID_API_KEY }}
      GOOGLE_MAPS_IOS_API_KEY: ${{ secrets.GOOGLE_MAPS_IOS_API_KEY }}
      EXPO_PUBLIC_REST_BACKEND_URL: ${{ vars.EXPO_PUBLIC_REST_BACKEND_URL }}
      EXPO_PUBLIC_WEBSOCKET_BACKEND_URL: ${{ vars.EXPO_PUBLIC_WEBSOCKET_BACKEND_URL }}
      EXPO_PUBLIC_GOOGLE_OAUTH_WEB_CLIENT_ID: ${{ vars.EXPO_PUBLIC_GOOGLE_OAUTH_WEB_CLIENT_ID }}
      EXPO_PUBLIC_GOOGLE_OAUTH_IOS_CLIENT_ID: ${{ vars.EXPO_PUBLIC_GOOGLE_OAUTH_IOS_CLIENT_ID }}
    outputs:
      ipa_artifact_name: ${{ steps.ipa.outputs.ipa_name }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Check environment variables
        if: inputs.profile != 'development'
        working-directory: apps/mobile
        run: pnpm check-env

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: pnpm install

      - name: Syncing app version code
        working-directory: apps/mobile
        run: eas build:version:sync --platform ios --profile ${{ inputs.profile }}

      - name: Compute IPA name
        id: ipa
        working-directory: apps/mobile
        run: |
          VERSION=$(npx expo config --json | jq -r '.version')
          VERSION_CODE=$(eas build:version:get -p ios --json --non-interactive | jq -r '.buildNumber')

          IPA_NAME=cityborn_${{ inputs.profile }}_v${VERSION}_${VERSION_CODE}.ipa
          IPA_PATH=${{ github.workspace }}/${IPA_NAME}

          echo "ipa_name=$IPA_NAME" >> $GITHUB_OUTPUT
          echo "ipa_path=$IPA_PATH" >> $GITHUB_OUTPUT

          echo "Computed IPA name: $IPA_NAME"

      - name: Build iOS app
        working-directory: apps/mobile
        run: eas build --platform ios --profile ${{ inputs.profile }} --local --non-interactive --output ${{ steps.ipa.outputs.ipa_path }}

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.ipa.outputs.ipa_name }}
          path: ${{ steps.ipa.outputs.ipa_path }}