on:
  workflow_call:
    inputs:
      backendHasChanged:
        type: string
        required: true
      frontendHasChanged:
        type: string
        required: true
      backofficeHasChanged:
        type: string
        required: true
      mobileHasChanged:
        type: string
        required: true

jobs:
  ios:
    name: Build iOS
    if: ${{ inputs.mobileHasChanged == 'true' }}
    uses: ./.github/workflows/build-ios.yml
    secrets: inherit
    with:
      environment: staging
      profile: staging

  android:
    name: Build Android
    if: ${{ inputs.mobileHasChanged == 'true' }}
    uses: ./.github/workflows/build-android.yml
    secrets: inherit
    with:
      environment: staging
      profile: staging