on:
  workflow_call:

jobs:
  ios:
    name: Build iOS
    uses: ./.github/workflows/build-ios.yml
    secrets: inherit
    with:
      environment: staging
      profile: staging

  android:
    name: Build Android
    uses: ./.github/workflows/build-android.yml
    secrets: inherit
    with:
      environment: staging
      profile: staging