on:
  workflow_call:
    inputs:
      backendHasChanged:
        type: string
        required: true
      frontendHasChanged:
        type: string
        required: true
      backofficeHasChanged:
        type: string
        required: true
      mobileHasChanged:
        type: string
        required: true

jobs:
  ios:
    name: Build iOS
    if: ${{ inputs.mobileHasChanged == 'true' }}
    uses: ./.github/workflows/build-ios.yml
    secrets: inherit
    with:
      environment: production
      profile: production

  android:
    name: Build Android
    if: ${{ inputs.mobileHasChanged == 'true' }}
    uses: ./.github/workflows/build-android.yml
    secrets: inherit
    with:
      environment: production
      profile: production
    
  frontend:
    name: Build Frontend
    if: ${{ inputs.frontendHasChanged == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Build Frontend
        run: echo "✅ Nothing to build"
  
  backend:
    name: Build Backend
    if: ${{ inputs.backendHasChanged == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Build Backend
        run: echo "✅ Nothing to build"

  back-office:
    name: Build Back Office
    if: ${{ inputs.backofficeHasChanged == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Build Back Office
        run: echo "✅ Nothing to build"