name: Prod - Continuous Deployment

on:
  workflow_dispatch:

jobs:
  get-tag:
    name: Get latest tag
    runs-on: ubuntu-latest
    outputs:
      releaseTag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 --match "v[0-9]*" --exclude "*-rc")
          echo $TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

  detect-changes:
    name: Detect changes
    needs:
      - get-tag
    uses: ./.github/workflows/detect-changes.yml
    with:
      base: ${{ needs.get-tag.outputs.releaseTag }}

  build-and-deploy-prod:
    name: Build + Deploy - Prod
    needs:
      - detect-changes
    secrets: inherit
    uses: ./.github/workflows/build-and-deploy-prod.yml
    with:
      backendHasChanged: ${{ needs.detect-changes.outputs.backendHasChanged }}
      frontendHasChanged: ${{ needs.detect-changes.outputs.frontendHasChanged }}
      backofficeHasChanged: ${{ needs.detect-changes.outputs.backofficeHasChanged }}
      mobileHasChanged: ${{ needs.detect-changes.outputs.mobileHasChanged }}

  create-release:
    name: Release
    needs:
      - get-tag
      - build-and-deploy-prod
    permissions:
      contents: write
    uses: ./.github/workflows/generate-release.yml
    with:
      releaseTag: ${{ needs.get-tag.outputs.releaseTag }}
      prerelease: false