name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  version:
    name: Version
    uses: ./.github/workflows/generate-version-number.yml

  tag:
    name: Tag
    needs: version
    permissions:
      contents: write
    uses: ./.github/workflows/create-tag.yml
    with:
      tag: ${{ needs.version.outputs.version }}

  create-wip-pre-release:
    name: Pre-release
    needs:
      - version
      - tag
    permissions:
      contents: write
    uses: ./.github/workflows/generate-release.yml
    with:
      release_tag: ${{ needs.version.outputs.version_rc }}
      prerelease: true

  build-staging:
    name: Build staging
    needs: tag
    secrets: inherit
    uses: ./.github/workflows/build-staging.yml
  deploy-staging:
    name: Deploy staging
    needs: build-staging
    secrets: inherit
    uses: ./.github/workflows/deploy-staging.yml