name: Staging - Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
      version_rc: ${{ steps.set-version.outputs.version_rc }}
    steps:
      - name: Set version
        id: set-version
        run: |
          VERSION="v${{ github.run_number }}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "version_rc=${VERSION}-rc" >> $GITHUB_OUTPUT

  create-wip-pre-release:
    name: Pre-release
    needs:
      - version
    permissions:
      contents: write
    uses: ./.github/workflows/generate-release.yml
    with:
      releaseTag: ${{ needs.version.outputs.version_rc }}
      prerelease: true

  tag:
    name: Tag
    needs: version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create tag
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag -a "${{ needs.version.outputs.version }}" -m "${{ needs.version.outputs.version }} - $(date +'%Y-%m-%d')"
          git push origin "${{ needs.version.outputs.version }}"

  detect-changes:
    name: Detect changes
    needs: version
    uses: ./.github/workflows/detect-changes.yml

  deploy-web-staging:
    name: Build + Deploy - Web - Staging
    needs:
      - detect-changes
    secrets: inherit
    uses: ./.github/workflows/build-and-deploy-web-staging.yml
    with:
      backendHasChanged: ${{ needs.detect-changes.outputs.backendHasChanged }}
      frontendHasChanged: ${{ needs.detect-changes.outputs.frontendHasChanged }}
      backofficeHasChanged: ${{ needs.detect-changes.outputs.backofficeHasChanged }}
