name: Prod - Continuous Deployment

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Type of release to create"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  get-tag:
    name: Get tags
    runs-on: ubuntu-latest
    outputs:
      lastProdTag: ${{ steps.get_tag.outputs.lastProdTag }}
      newReleaseTag: ${{ steps.get_tag.outputs.newReleaseTag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tags
        id: get_tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          LAST_PROD=$(gh release list --repo ${{ github.repository }} --exclude-pre-releases --limit 1 --json tagName --jq '.[0].tagName')
          NEW_RELEASE=$(git describe --tags --abbrev=0 --match "v[0-9]*" --exclude "*-rc")
          echo "lastProdTag=$LAST_PROD" >> $GITHUB_OUTPUT
          echo "newReleaseTag=$NEW_RELEASE" >> $GITHUB_OUTPUT

  detect-changes:
    name: Detect changes
    needs:
      - get-tag
    uses: ./.github/workflows/detect-changes.yml
    with:
      base: ${{ needs.get-tag.outputs.lastProdTag }}

  build-and-deploy-web-prod:
    name: Build + Deploy - Web - Prod
    needs:
      - detect-changes
    secrets: inherit
    uses: ./.github/workflows/build-and-deploy-web-prod.yml
    with:
      backendHasChanged: ${{ needs.detect-changes.outputs.backendHasChanged }}
      frontendHasChanged: ${{ needs.detect-changes.outputs.frontendHasChanged }}
      backofficeHasChanged: ${{ needs.detect-changes.outputs.backofficeHasChanged }}

  create-release:
    name: Release
    needs:
      - get-tag
      - build-and-deploy-web-prod
    permissions:
      contents: write
    uses: ./.github/workflows/generate-release.yml
    with:
      releaseTag: ${{ needs.get-tag.outputs.newReleaseTag }}
      prerelease: false
