name: Tag

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  push_tag:
    name: Create & push ${{ inputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create tag
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag -a "${{ inputs.tag }}" -m "${{ inputs.tag }} - $(date +'%Y-%m-%d')"
          git push origin "${{ inputs.tag }}"