name: Deploy Staging

on:
  workflow_call:

jobs:
  frontend:
    name: Deploy Frontend
    uses: ./.github/workflows/deploy-to-vercel.yml
    secrets: inherit
    with:
      environment: staging
      project_id: ${{ vars.VERCEL_FRONTEND_PROJECT_ID }}

  back-office:
    name: Deploy Back Office
    uses: ./.github/workflows/deploy-to-vercel.yml
    secrets: inherit
    with:
      environment: staging
      project_id: ${{ vars.VERCEL_BACK_OFFICE_PROJECT_ID }}

  backend:
    name: Deploy Backend
    uses: ./.github/workflows/deploy-to-railway.yml
    secrets: inherit
    with:
      environment: staging
      service_id: ${{ vars.RAILWAY_BACKEND_SERVICE_ID }}