name: Deploy frontend

on:
  push:
    branches:
      - staging
    paths:
      - 'apps/frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Hook
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_STAGING_URL }}
