name: Deploy Production Backend to Railway

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'apps/backend/**'
      - 'packages/types/**'
      - 'package/errors/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: productionu

    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy
        run: railway up --service=${{ secrets.RAILWAY_BACKEND_SERVICE_ID }} --environment=production --ci
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}