name: Deploy Staging

on:
  workflow_call:

jobs:
  deploy-frontend-staging:
    uses: ./.github/workflows/deploy-to-vercel.yml
    secrets: inherit
    with:
      environment: staging
      project_id: ${{ vars.VERCEL_FRONTEND_PROJECT_ID }}

  deploy-back-office-staging:
    uses: ./.github/workflows/deploy-to-vercel.yml
    secrets: inherit
    with:
      environment: staging
      project_id: ${{ vars.VERCEL_BACK_OFFICE_PROJECT_ID }}

  deploy-backend-staging:
    uses: ./.github/workflows/deploy-to-railway.yml
    secrets: inherit
    with:
      environment: staging
      service_id: ${{ vars.RAILWAY_BACKEND_SERVICE_ID }}

  build-ios-staging:
    uses: ./.github/workflows/ios-build-staging.yml
    secrets: inherit

  build-android-staging:
    uses: ./.github/workflows/android-build-staging.yml
    secrets: inherit