name: Detect changes

on:
  workflow_call:
    outputs:
      backendHasChanged:
        value: ${{ jobs.detect-changes.outputs.backendHasChanged }}
      frontendHasChanged:
        value: ${{ jobs.detect-changes.outputs.frontendHasChanged }}
      backofficeHasChanged:
        value: ${{ jobs.detect-changes.outputs.backofficeHasChanged }}
      mobileHasChanged:
        value: ${{ jobs.detect-changes.outputs.mobileHasChanged }}

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backendHasChanged: ${{ steps.filter.outputs.backendHasChanged }}
      frontendHasChanged: ${{ steps.filter.outputs.frontendHasChanged }}
      backofficeHasChanged: ${{ steps.filter.outputs.backofficeHasChanged }}
      mobileHasChanged: ${{ steps.filter.outputs.mobileHasChanged }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontendHasChanged:
              - 'apps/frontend/**'
              - 'packages/**'

            backendHasChanged:
              - 'apps/backend/**'
              - 'packages/**'

            backofficeHasChanged:
              - 'apps/back-office/**'
              - 'packages/**'

            mobileHasChanged:
              - 'apps/mobile/**'
              - 'packages/**'